### ISSUE TITLE
Group permission does not work

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_audit#1]
Hi there,

I'm not sure if this is being handle by Cacti or per plugin. In any case, please advise.

I created a Group to manage permissions and it doesn't work by group or user, meaning that the option is not desplayed. I did try giving permissions to other plugins. Audit and weathermap are the only two not working.

Since it's shown as an option under "Plugin permissions" I thought it should work.

Running Cacti 1.1.12

**Comment by cigamit** [comment]
You don't have to do anything special to confirm group permissions.  You just use the api to add the realm, and then grant the user group permission to the realm.  The following api function in lib/auth.php is then called to verify if the user/group combination has permission to the realm:

`function is_realm_allowed($realm) {}`

That's all there is to it.  I recommend you talk to Howie about his use of standard permissions.  Right now, he has his own permission system that does not recognize the Cacti Groups presently.  Audit, I'm surprised just a little.  It's kind of a simple plugin.

**Comment by cigamit** [comment]
I found the issue.  Resolving.  So, ignore everything I said.  I was showing the View Audit Log even when the user did not have permission.  The update fixes that.
