### ISSUE TITLE
Cacti 1.2.3  Auti plugin showing error when click on Main console

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_audit#4]
Hey Everyone 

Seeing the following error with  Audit plugin installed

![image](https://user-images.githubusercontent.com/13388748/57793506-786af100-770f-11e9-9367-5b867b208332.png)

and indeed the index.php file is not included in the latest git clone 

drwxr-xr-x 5 www-data www-data  4096 May 15 12:37 ./
drwxrwxr-x 7 www-data www-data  4096 May 15 12:38 ../
-rw-r--r-- 1 www-data www-data 17887 May 15 12:37 audit.php
drwxr-xr-x 8 www-data www-data  4096 May 15 12:37 .git/
drwxr-xr-x 3 www-data www-data  4096 May 15 12:37 .github/
-rw-r--r-- 1 www-data www-data     7 May 15 12:37 .gitignore
-rw-r--r-- 1 www-data www-data   243 May 15 12:37 INFO
-rw-r--r-- 1 www-data www-data 15237 May 15 12:37 LICENSE
drwxr-xr-x 4 www-data www-data  4096 May 15 12:37 locales/
-rw-r--r-- 1 www-data www-data  1056 May 15 12:37 README.md
-rw-r--r-- 1 www-data www-data 10584 May 15 12:37 setup.php
-rw-r--r-- 1 www-data www-data  1039 May 15 12:37 .travis.yml

Here is a snapshot of the settings page

![image](https://user-images.githubusercontent.com/13388748/57793612-c2ec6d80-770f-11e9-8f89-bb2b94091a0e.png)

**Comment by bmfmancini** [comment]
Oh sorry BTW to replicate 

Click Utilities >> System utilities >> View audit log >>Main Console 

But if you click on something else all is good

**Comment by cigamit** [comment]
This should be fixed now.
