### ISSUE TITLE
[Feature Request] See the actual change 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_audit#5]
Hey Everyone 

One thing that would be nice to see is a way to find out what was changed 
right now the most info you get is that there was a save but that could be harmless like changing of the user's profile settings to a system change 

If the post message could be somehow displayed to show exactly what was changed that would be awesome

**Comment by cigamit** [comment]
This will take a little extra work, as for each change you would have to first pull the existing data, and loop through the new data and check for differences and then record them.  If we just took the entire post, it wouldn't really do any good as you don't know what the before values were.  I did this in another app I wrote, so its not too difficult but it could become tricky to apply across every type of change.

**Comment by netniV** [comment]
We must already do that to detect that a change was made as we report this on clock to other pages. There is a JS array that is used so making a dialog for the save would be done before submit effectively

**Comment by TheWitness** [comment]
Once we complete the data reduction in 1.3 (crossing my fingers), this will be much easier to track.

**Comment by bmfmancini** [comment]
Im working on this now
